import Vue from 'vue';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBold,
  faCaretDown,
  faCaretUp,
  faEllipsisH,
  faEllipsisV,
  faEnvelopeOpen,
  faItalic,
  faUnderline,
  faStrikethrough,
  faLink,
  faQuoteRight,
  faTable,
  faUndo,
  faRedo,
  faList,
  faListOl,
  faUnlink,
  faParagraph,
  faListUl,
  faMinus,
  faAlignLeft,
  faAlignCenter,
  faAlignRight,
  faSquare,
} from '@fortawesome/free-solid-svg-icons';
import {
  faFacebook,
  faGoogle,
  faMicrosoft,
} from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
library.add(
  faBold,
  faCaretDown,
  faCaretUp,
  faEllipsisH,
  faEllipsisV,
  faEnvelopeOpen,
  faFacebook,
  faGoogle,
  faMicrosoft,
  faItalic,
  faUnderline,
  faStrikethrough,
  faLink,
  faQuoteRight,
  faTable,
  faUndo,
  faRedo,
  faList,
  faListOl,
  faUnlink,
  faParagraph,
  faListUl,
  faMinus,
  faAlignLeft,
  faAlignCenter,
  faAlignRight,
  faSquare
);
Vue.component('font-awesome-icon', FontAwesomeIcon);
